# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79626ee646042a2012535e0fe113756ed3d838f9c1a1d1a3124a4acb543790e0b38178a5ee6955c99020b4827aaca0e7fc9f3663cda606e125704d947e77cf3a

test:
  secret_key_base: f454770d7010f085c5c28e7930e4e2a9aa30aa6006efc6e367209bcb0c541a450e27f2c26822ca4f1299b189edbc4a5d7585874a349668e5c82a18249f67b607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
